language: java

jdk:
  - oraclejdk8
    - oraclejdk7
      - openjdk6

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script:
  - ./gradlew check
  - ./gradlew seleniumXvfb
  - python bin/send_latest_jar.py

notifications:
  email:
    recipients:
      - bjoggib@gmail.com
    on_success: always
    on_failure: always


deploy:
  provider: heroku
  api-key:
    secure: "a8f14d51-efc4-417f-8b62-57e5ec74ad33"
  app: 
    develop: warm-sierra-2216
    master: tictactoe-dj-scrum

after_deploy:
  - python bin/send_latest_reports.py
